# Copyright © 2017 VMware, Inc. All Rights Reserved.
---
sudo: required
language: python
cache: pip
install:
  - pip install ansible-lint
script:
  - ansible-lint  ./tests/travis-playbook.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
