# Copyright © 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
sudo: required
language: python
services:
  - docker
install:
  - pip install molecule
  - pip install docker
script:
  - cd ..
  - mv ansible-role-vmware-workstation vmware-workstation
  - cd vmware-workstation
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
