# Copyright © 2017 VMware, Inc. All Rights Reserved.
---
sudo: required
language: python
services:
  - docker
install:
  - pip install molecule
  - pip install docker
script:
  - >
    sed -i.orig 's;  playbook.*;  playbook: tests/travis-playbook.yml;' molecule.yml
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
