# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- name: Setup VMware Workstation Facts
  set_fact: workstation_extra_packages={{ os_workstation_extra_packages }}
  when: workstation_extra_packages is undefined and
        os_workstation_extra_packages is defined

- name: Create temp directory
  file:
    path: "{{ workstation_tempdir }}"
    state: directory
    mode: 0755

- name: Check VMWare workstation version
  shell: >
    vmware --version
  register: vmware_version
  ignore_errors: true

- name: Download workstation
  get_url:
    url: "{{ workstation_download_url }}"
    dest: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
  when: vmware_version.stdout.find(workstation_current_version) == -1

- name: Mark script executable
  file:
    path: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
    state: file
    mode: 0755

- name: Run installer
  shell: >
    {{ workstation_tempdir }}/tryworkstation-linux-64.sh --eulas-agreed --console
    --required {{'--set-setting vmware-workstation serialNumber '+ workstation_license if workstation_license is defined else '' }}
  args:
    creates: /usr/bin/vmware
  become: true
  tags:
    - skip_ansible_lint

- name: Install packages needed by vmware packer build
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ workstation_extra_packages }}"
  become: true
  when: workstation_extra_packages is defined

- name: Stat for systemd
  stat:
    path: /etc/systemd/system
  register: systemd_dir

- name: Install systemd services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - vmware.service
    - vmware-usbarbitrator.service
    - vmware-workstation-server.service
  when: systemd_dir.stat.exists
  notify: Reload SystemD Configurations
